version: '2.0'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_database:/data/db
    environment:
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=example
      - MONGO_INTDB_DATABASE=testdb
    
  api:
    build: api/.
    ports:
      - "8086:8086"
    environment:
      - PORT=8086
    develop:
      watch:
        - action: sync
          path: api/src
          target: /usr/src/app
        - action: rebuild
          path: api

volumes:
  mongo_database:
