version: '1.0'

services:
  mongo:
    images: mongo:4.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=example
      - MONGO_INTDB_DATABASE=testdb

  server:
    build: api/.
    restart: always
    ports:
      - "8086:8086"
    environment:
      - 
      - 
      - 
